name: Build-Ci

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: loxicmd-build-ci

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build loxicmd
      run: make
