name: Build-Ci

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: loxicmd-build-ci

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
        with:
             go-version: '>=1.17.0'

    - name: Build loxicmd
      run: make
